apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: s56vr9fqo-go
  janus-idp.io/tekton: s56vr9fqo-go
  backstage.io/kubernetes-id: s56vr9fqo-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: s56vr9fqo-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
